# Generated by Django 2.2.5 on 2019-12-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20191214_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='银行名称')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('point', models.CharField(max_length=60, verbose_name='网点')),
            ],
            options={
                'verbose_name_plural': '银行卡',
            },
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=30, verbose_name='卡号')),
                ('card_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Bank', verbose_name='选择银行')),
            ],
            options={
                'verbose_name_plural': '卡号信息',
            },
        ),
    ]
