# Generated by Django 2.2.5 on 2019-12-29 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_card_carddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=50, verbose_name='银行名称')),
                ('city', models.CharField(default='', max_length=30, verbose_name='城市')),
                ('point', models.CharField(default='', max_length=60, verbose_name='网店')),
            ],
            options={
                'verbose_name': '银行',
                'verbose_name_plural': '银行',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='bank_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hello.BankName'),
        ),
    ]
