# Generated by Django 2.2.5 on 2019-12-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20191229_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carddetail',
            options={'verbose_name': '账户_个人资料', 'verbose_name_plural': '账户_个人资料'},
        ),
        migrations.AlterField(
            model_name='bankname',
            name='point',
            field=models.CharField(default='', max_length=60, verbose_name='网点'),
        ),
    ]
