# Generated by Django 2.2.5 on 2019-12-29 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20191229_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nub', models.CharField(default='', max_length=50, verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '会员等级',
                'verbose_name_plural': '会员等级',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='bank_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='card_bank', to='hello.BankName'),
        ),
        migrations.AddField(
            model_name='card',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='card_grade', to='hello.CardGrade'),
        ),
    ]
