# Generated by Django 2.2.5 on 2019-12-30 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_articleclassify_articledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='classify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classify_name', to='hello.ArticleClassify', verbose_name='文章分类'),
        ),
    ]
